name: Test Install with Apache CGI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Apache and Enable CGI
      run: |
        sudo apt-get update
        sudo apt-get install -y apache2
        sudo a2enmod cgi

    - name: Install python2 and gnuplot
      run: |
        sudo apt-get install python2
        sudo apt-get install gnuplot

    - name: Check shell script syntax with BASH
      run: |
        for i in $(find -name '*.sh') ;do /usr/bin/env bash -n "$i" || exit 1 ;done

    - name: Compile the code
      run: |
        cd cgi-bin/lk || exit 1
        make

    - name: Create and mount temporary data directory
      run: |
        sudo mkdir /space
        sudo mount -t tmpfs -o size=1G,mode=0777 tmpfs /space

    - name: Configure Apache to Enable CGI
      run: |
        sudo tee /etc/apache2/sites-available/000-default.conf > /dev/null <<EOF
        <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html
            ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
            <Directory "/usr/lib/cgi-bin">
             AllowOverride None
             Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
             SetHandler cgi-script
             Require all granted
            </Directory>
            ErrorLog /var/log/apache2/error.log
            CustomLog /var/log/apache2/access.log combined
        </VirtualHost>
        EOF
        sudo systemctl restart apache2

    - name: Copy Web Application Files to cgi-bin
      run: |
        sudo mkdir -p /usr/lib/cgi-bin/lk
        sudo cp -r cgi-bin/lk/* /usr/lib/cgi-bin/lk/

    - name: Change Owner of CGI Scripts
      run: |
        sudo chown -R www-data:www-data /usr/lib/cgi-bin/lk/

    - name: Copy Static Web Pages
      run: |
        sudo mkdir -p /var/www/html/lk
        sudo cp -r htdocs/lk/* /var/www/html/lk/
        sudo chown -R www-data:www-data /var/www/html/lk/

    - name: Test Apache Server
      run: |
        curl -I http://localhost/cgi-bin/lk/process_lightcurve.py

    - name: Test Web Pages Accessibility
      run: |
        curl -I http://localhost/lk/index.html

    - name: Run the Application Test Script
      run: |
        test_lightcurves/test_localhost.sh

    - name: Display Apache Error Log
      if: failure()
      run: |
        echo "Displaying Apache Error Log:"
        cat /var/log/apache2/error.log

    - name: Display Apache Access Log
      if: failure()
      run: |
        echo "Displaying Apache Access Log:"
        cat /var/log/apache2/access.log
